### ISSUE TITLE
Possibly wrong encoding for int8

### ISSUE THREAD

**Issue by coolwanglu** [mcollina/msgpack5#14]
`-1` is encoded to [225], but other implementations encode it to [255]

[This line](https://github.com/mcollina/msgpack5/blob/master/index.js#L399) seems to be questionable.

[The spec](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-int) does not mention to find the compliment code with the mask of `0xe0`. I also took a look at other implementation, all of them directly convert the byte to a negative number;

- C / Python (borrowed from C): https://github.com/msgpack/msgpack-python/blob/master/msgpack/unpack_template.h#L175
- C++: https://github.com/Lichtso/netLink/blob/master/src/MsgPack.cpp#L86
- Rust: https://github.com/mneumann/rust-msgpack/blob/master/src/lib.rs#L113

So I guess we should also do the same here?

**Comment by mcollina** [comment]
I think so, yes. Would you like to submit a PR for this?

**Comment by coolwanglu** [comment]
See #15
