### ISSUE TITLE
Can't encode/decode a Date object

### ISSUE THREAD

**Issue by xsellier** [mcollina/msgpack5#19]
Try this code:

```javascript
var msgpack5  = require("msgpack5")();
var date = new Date();
console.log(date);
var result = msgpack5.decode(msgpack5.encode( {"date": date}));
console.log(result);
```

Output:

      Tue Mar 17 2015 11:17:52 GMT-0400 (EDT)
      { date: {} }

**Comment by mcollina** [comment]
Date is not included in the spec: https://github.com/msgpack/msgpack/blob/master/spec.md

I think it would be great if you write a little module that register an extension for encoding a Date, given a `msgpack5` instance. If you are willing to write that module, I would definitely list in the README.

You should use https://github.com/mcollina/msgpack5#registerencodercheckobj-encodeobj and https://github.com/mcollina/msgpack5#registerdecodertype-decodebuf

**Comment by xsellier** [comment]
Thank you for the quick answer, I will write a specific encoder/decoder for "Date" object.
