### ISSUE TITLE
using msgpack + encryption

### ISSUE THREAD

**Issue by behrad** [mcollina/msgpack5#21]
I was looking for a small footprint payload format for between my MQTT connections, I faced `ubjson` and `messagePack` and then found you again @mcollina ;) Not completely related to this repo, but why not to ask you here? :p

1) is messagePack superior to ubjson for mqtt in mobile apps? I have node.js + Java clients
2) I want (end to end) encryption of payload for security reasons, which standard/library dya recommend for this?

**Comment by mcollina** [comment]
1) here you can send custom types, which is not supported by ubjson. They both do the same thing. I can guess that ubjson is faster to parse (given that the spec is easier), but that is also library-dependant
2) I just recommend a 'correct' setup of TLS, using the most recent cyphers.

**Comment by behrad** [comment]
:+1:
