### ISSUE TITLE
Use msgpack5 in the browser

### ISSUE THREAD

**Issue by drawmindmap** [mcollina/msgpack5#26]
I get this error when i use msgpack5 in the browser:
msgpack5_bundle.js:3015 Uncaught TypeError: this.once is not a function

    <!DOCTYPE html>
    <head>
      <meta charset="UTF-8">
      <title>Test msgpack5</title>
      <script src="msgpack5_bundle.js"></script>
      <script>
    function init() {
      msgpack = msgpack5();
      console.log(msgpack.decode(msgpack.encode('Test')));
    }
      </script>
    </head>
    <body onload="init()">
    </body>
    </html>

**Comment by mcollina** [comment]
How did you do your bundle?

Probably it's missing a require('stream') at the very beginning.
Il giorno mer 24 giu 2015 alle 03:21 drawmindmap <notifications@github.com>
ha scritto:

**Comment by drawmindmap** [comment]
From https://github.com/mcollina/msgpack5/blob/master/dist/msgpack5_bundle.js
Run 'npm run browserify', it ok now using dist/msgpack5.js

**Comment by cxh80301983** [comment]
create a  test.js
code  
>global.msg =require("msgpack5")();

browserify test.js -s msgpack -o client.js

**Comment by mcollina** [comment]
I have updated the bundles, please check again.

**Comment by cxh80301983** [comment]
thank you
