### ISSUE TITLE
how to use on Browser  of client 

### ISSUE THREAD

**Issue by cxh80301983** [mcollina/msgpack5#27]
![qq20150704-1 2x](https://cloud.githubusercontent.com/assets/1124832/8506725/b93481e6-2255-11e5-9464-3374084d539d.png)
> var ss = {a:1,b:2}
  //  res.send({a:1})
      res.set("Content-Type","application/msgpack");
      console.log(msg.encode(ss));
      res.end(msg.encode(ss));

how can i  get  this data  on client  ?

**Comment by mcollina** [comment]
You have to transfer the data as binary: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data
