### ISSUE TITLE
Clarification on supported browsers

### ISSUE THREAD

**Issue by Stratus3D** [mcollina/msgpack5#28]
I have been using this library with a couple browsers and it seems to be working fine in all of them except IE 10. The readme doesn't clarify what browsers are supported, so I assume that IE 10 isn't currently supported.

* Is there a list of browsers that are supported by msgpack5?
* If IE 10 is not supported, do you any idea what it would take to get it working on IE? Are there any things that stand out to you as obliviously not working in IE 10?
* It seems like the library uses `Error.captureStackTrace` on https://github.com/mcollina/msgpack5/blob/master/lib/decoder.js#L6. This of course isn't supported by IE 10.

**Comment by mcollina** [comment]
This library depends on TypedArrays, see https://github.com/feross/buffer. TypedArrays are available with limitations on IE10, which might be the issue.

If you do some proper testing and want to share the result, just send a PR (even update the test suite to run on saucelabs with [zuul](http://npm.im/zuul)).

**Comment by mcollina** [comment]
Side note: I wrote this library for node.js consumption, so I _never_ tested it on browsers.

**Comment by mcollina** [comment]
@Stratus3D if the `Error.captureStackTrace` is the only thing that is limiting supporting IE10, then we should work around it.

Anyway, I think support for IE10 is feasible, so if you want to attack the problem and send a PR, please do :).

**Comment by Stratus3D** [comment]
Have you ever thought of using https://ci.testling.com/ integration? I haven't used it before but looks like it might help determine what browsers are supported. It's free for open source projects. All you need to do is configure a web hook.

I'll create a PR if I am able to get the library working in IE 10.

**Comment by mcollina** [comment]
I have used [saucelabs](http://saucelabs.com) before, and it works great. Examples: https://github.com/feross/buffer and https://github.com/mcollina/levelgraph.

**Comment by Stratus3D** [comment]
Saucelabs would be great too. For me it seems like the pre-commit hook only tests in nodejs. For pre-commit that is probably fine, but it would be nice to also see something like the saucelabs results at the top of the README like you have for your other projects.

Anyway, we found the source of our problem: since encode returns an ArrayBuffer, we were passing that directly to be written a websocket.  Our server's msgpack v5 impl, written in Erlang, could not decode messages sent by IE10.  When wrapping the resulting ArrayBuffer returned from encode in a Uint8Array and writing that to the websocket, our server was able to decode messages sent by IE10.

    // When sending as a WebSocket message
    // This failed:
    var encodedMsg = msgpack.encode(msg)
    
    // But this worked:
    var encodedMsg = new Uint8Array(msgpack.encode(msg))

This is the Erlang library we are using: https://github.com/msgpack/msgpack-erlang

Since there isn't anything with msgpack5 that we know is causing issues IE 10 I don't think I will be submitting any other PRs. 

Thanks for your help!

**Comment by mcollina** [comment]
That's great!
