### ISSUE TITLE
float inaccuracy

### ISSUE THREAD

**Issue by hden** [mcollina/msgpack5#30]
* node: `v0.12.2`
* msgpack5: `^3.0.0`

```js
var msgpack = require('msgpack5')()
msgpack.decode(msgpack.encode(3.14))
// 3.140000104904175
```

**Comment by mcollina** [comment]
Technically it's a float, so it can be accurate.

**Comment by hden** [comment]
@mcollina At least use a float 64, consistent with the official [demo](http://msgpack.org/index.html)
<img width="475" alt="screen shot 2015-07-21 at 11 19 41 pm" src="https://cloud.githubusercontent.com/assets/1910549/8804494/214b2cce-2fff-11e5-9a58-6d7721fb3b4c.png">

**Comment by mcollina** [comment]
JS do not have a float type, all numbers are 64-bits doubles. Currently this library uses float32 for small values, and float64 for big ones.

See https://github.com/mcollina/msgpack5/blob/master/test/floats.js https://github.com/mcollina/msgpack5/blob/master/test/doubles.js

I did this to optimize the data transfer.

It might be an option in the encoder to always use float64. Would you like to send a PR?
