### ISSUE TITLE
how can i decode the serialized string

### ISSUE THREAD

**Issue by demohi** [mcollina/msgpack5#33]
```javascript
var test = {hello: 'world' };
var serialized = msgpack.encode(test).toString();

// how can i decode the serialized string ?
```

**Comment by mcollina** [comment]
You can't. msgpack5 is a __binary__ protocol. If your transport can only send texts, you might consider serializing it to base64, and reading it back. However this would vanish all size gains that using msgpack will given you.

**Comment by demohi** [comment]
Thanks @mcollina
