### ISSUE TITLE
Move to standard

### ISSUE THREAD

**Issue by mcollina** [mcollina/msgpack5#34]
I think we should conform to @feross http://npm.im/standard.
This library is getting some traction now (13k downloads/month), so it can help spread the format.
The fact that this is basically done is useful for a smoke test perspective of standard as well :).

**Comment by mcdonnelldean** [comment]
+1 From me STANDARD ALL THE THINGS!

**Comment by feross** [comment]
Now, 150K+ downloads/month :smile: 

Here's a free PR to help you out: https://github.com/mcollina/msgpack5/pull/43

(This was a good chance for me to try out `standard-format` on a real-world project to see how practical it is to migrate larger codebases. Worked pretty well, though it still needed some manual help.)
