### ISSUE TITLE
Compatibility mode for str8

### ISSUE THREAD

**Issue by onderweg** [mcollina/msgpack5#45]
With my [deserializer](https://github.com/msgpack/msgpack-objectivec), I ran in to the issue described here:

http://stackoverflow.com/questions/19466343/msgpack-packing-of-string-values-longer-than-32-characters-in-python

Summary: my deserializer can't handle the str8 datatype.

Is it possible to support compatibility mode for encoding, as described in the [MessagePack specs](https://github.com/msgpack/msgpack/blob/master/spec.md#formats-str)?

>serializers should offer "compatibility mode" which doesn't use bin format family and str 8 format

Thanks!

**Comment by mcollina** [comment]
I have no time to add features to this library, but yes, it would be nice. If you or anyone else would like to send a PR, I'd be happy to review and merge.

**Comment by onderweg** [comment]
Okay, I will prepare a pull request.

**Comment by onderweg** [comment]
Done.

**Comment by mcollina** [comment]
Released as 3.4.0.
