### ISSUE TITLE
Why can't a registered type be 0?

### ISSUE THREAD

**Issue by fritzy** [mcollina/msgpack5#5]
neovim sets up a type as 0. If I disable the !== 0 asserts for registering, it works great.

**Comment by tarruda** [comment]
FWIW, I've pushed a msgpack5 rpc implementation: https://www.npmjs.com/package/msgpack5rpc and a neovim client on top of that: https://www.npmjs.com/package/neovim-client

**Comment by mcollina** [comment]
Wow, that's amazing! Feel free to send a PR for this project README, so
that we link each other!

>
