### ISSUE TITLE
Add an option to support predicable encoding

### ISSUE THREAD

**Issue by hh9527** [mcollina/msgpack5#52]
```js
// file: lib/encoder.js:201 function encodeObject
    for (key in obj) {
      if (obj.hasOwnProperty(key) &&
        obj[key] !== undefined &&
        typeof obj[key] !== 'function') {
        ++length
        acc.push(encode(key, true))
        acc.push(encode(obj[key], true))
      }
    }
```

this will cause the properties order is unpredicable, that will cause some digest mechanism will failed: same value in different case produce different encoded result.

**Comment by mcollina** [comment]
It follows the same order as JSON.

**Comment by hh9527** [comment]
Yes, it follows the order from JSON. but JSON's order is unpredicable. so MsgPack is also unpredicable.

**Comment by mcollina** [comment]
Send a PR AND i will review it.
