### ISSUE TITLE
support for map that holds more than 65535 keys

### ISSUE THREAD

**Issue by kyriosli** [mcollina/msgpack5#54]
When encoding an key-value map, the `encoder` treats keys that more than 16 as just less than 65536, which may cause problem when serializing objects with large amount of keys, as shown [here](https://github.com/mcollina/msgpack5/blob/master/lib/encoder.js#L214). I might issue a pull request as soon as I finished the full compatibility tests if you shall not be available for a fix, but plz be kind enough to push a new release on `npm` after then, ^_^

**Comment by mcollina** [comment]
Please send a PR :). I'm low on bandwidth atm.
