### ISSUE TITLE
Why is Uint8Array serialized as map?

### ISSUE THREAD

**Issue by moozzyk** [mcollina/msgpack5#58]
I am using msgpack5 in a browser and when I try to pack `new Uint8Array([1, 2, 3])` I get the following payload `0x83 0xa1 0x30 0x01 0xa1 0x31 0x02 0xa1 0x32 0x03` which is a map. I expected to get a `bin8`. Looking at [the code](https://github.com/mcollina/msgpack5/blob/3ab63aeb8b403a4a6c9bd0c6ada1b7dc60caf083/lib/encoder.js#L48) it appears that `binX` would work for Buffer but because msgpack5 is wrapped in a library/module the Buffer does not seem to be available outside the library.

**Comment by mcollina** [comment]
it’s a bug! Would you like to send a PR?

**Comment by moozzyk** [comment]
Hactoberfest, here I come! (I will try to submit a PR in the coming days).
