### ISSUE TITLE
Fix for #58 missing in bundled file

### ISSUE THREAD

**Issue by anurse** [mcollina/msgpack5#62]
The fix for #58 appears to only be present in the `lib/encoder.js` file in the package, not the bundled `dist/msgpack5.js` file.

See `encoder.js`:

https://github.com/mcollina/msgpack5/blob/c504ca7e1133b517ac571a7eaed57c40fc14b316/lib/encoder.js#L48-L53

Compared to `msgpack5.js`:

https://github.com/mcollina/msgpack5/blob/c504ca7e1133b517ac571a7eaed57c40fc14b316/dist/msgpack5.js#L534-L536

Sounds like maybe the bundle just hasn't been updated 😄

**Comment by mcollina** [comment]
Fixed in 4.0.1.
