### ISSUE TITLE
Error "undefined is not encodable in msgpack"

### ISSUE THREAD

**Issue by skerit** [mcollina/msgpack5#64]
Is there a reason why `undefined` is so, err, disliked in this package?

I don't seem to be able to register an encoder for it, it's just hard coded in the `encoder.js` file to throw an error.

The `msgpack-node` implementation just encodes `undefined` values to `null`, and that's what I'd like to accomplish.

**Comment by skerit** [comment]
Of course, but why not let us register an encoder for `undefined`?

**Comment by mcollina** [comment]
Would you like to send a pr?
