### ISSUE TITLE
[snyk test] newer bl is needed as a dependency

### ISSUE THREAD

**Issue by jisoolee** [mcollina/msgpack5#83]
When I run snyk test, the result shows
```
✗ Remote Memory Exposure [High Severity][https://snyk.io/vuln/SNYK-JS-BL-608877] in bl@2.2.0
    introduced by msgpack5@4.2.1 > bl@2.2.0
  This issue was fixed in versions: 2.2.1, 3.0.1, 4.0.3
```

More details: https://snyk.io/vuln/SNYK-JS-BL-608877

Could you update package.json to pick up higher version of bl?

Thank you in advance.

**Comment by mcollina** [comment]
You should just update your dependendencies, the current version range includes the one with the fix.
